image: maven:3.6.1-jdk-11

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"
  DOCKER_IMAGE_TO_SCAN: registry.gitlab.com/parrot55/devops-webapp:latest

# Cache the Maven repository so that each job does not have to download it.
cache:
  key: mavenrepo
  paths:
    - ./.m2/repository/

stages:
  - build
  - release
  - create_docker_image
  - scan_docker_image
  - push_docker_image

# Run tests.
build:
  stage: build
  before_script:
      # Remove the SNAPSHOT from the project's version thus creating the release version number.
    - 'mvn $MAVEN_CLI_OPTS versions:set -DremoveSnapshot -DprocessAllModules=true'
    - 'export RELEASE_VERSION=$(mvn --batch-mode --no-transfer-progress --non-recursive help:evaluate -Dexpression=project.version | grep -v "\[.*")'
    - 'echo "Release version: $RELEASE_VERSION"'
  
  script:
    - 'mvn $MAVEN_CLI_OPTS install'

# Build a Docker image.
# Action can be manually triggered in the GitLab CI/CD pipeline
# of release tags.
create-docker-image:
  stage: create_docker_image
  image: docker:19.03.12
  #before_script:
    # Install a Docker client in the container as to be able to build Docker image(s).
    #- wget -q https://download.docker.com/linux/static/stable/x86_64/docker-19.03.12.tgz
    #- tar zxvf docker*.tgz
    #- cp docker/docker /usr/local/bin/docker
  script:
    - mvn docker:build

# Push the Docker image to a repository.
# In this example the repository is DockerHub.
push-docker-image:
  stage: push_docker_image
  when: manual
  script:
#    - docker login --username ivan --password secret
    - docker push registry.gitlab.com/parrot55/devops-webapp:latest
  only:
    - /^\d+\.\d+\.\d+$/
    - tags